onboarding = false

[terminal]
new_cwd = "follow"

[keys]
remove_worktree = "prefix+alt+g"
prefix = "ctrl+a"

[ui.toast]
delivery = "terminal"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[theme]
name = "terminal"
auto_switch = false
